package:
  name: filez
  version: "1.0.2"

source:
  path: ../

requirements:
  build:
    - python {{ python }}
  host:
    - python {{ python }}
  run:
    - python {{ python }}

build:
  noarch: python
  
test:
  # Python imports
  imports:
    - filez

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  requires:
    # Put any additional test requirements here.  For example
    - pytest

about:
  license: GPLv3
  license_family: GPL

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
